name: Validar Script Shell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Validar script con ShellCheck
        run: shellcheck mi_script.sh || (echo "::error::Error en ShellCheck" && exit 1)
